### ISSUE TITLE
Add payroll demo kit

### ISSUE THREAD

**Issue by sohkai** [aragon/dao-kits#15]

**Comment by Quazia** [comment]
What's the difference between a demo kit and a regular kit? #14

**Comment by sohkai** [comment]
@Quazia The demo kits are usually for us to include some mocked data for easier development of their corresponding apps. You can see the (outdated) demo kit for Survey (https://github.com/aragon/dao-kits/pull/9), which [basically just adds some mock data](https://github.com/aragon/dao-kits/pull/9/files#diff-659ab2c45f2c8552fc06ca8a8ee6e7a5R98).

**Comment by sohkai** [comment]
Closing since the Payroll app has its own demo kit included as part of its files.
