### ISSUE TITLE
Change default permissions so that only an account who belongs to an organisation can create new votes.

### ISSUE THREAD

**Issue by marsrobertson** [aragon/dao-kits#53]
Anyone who knows the URL of my organisation (it's blockchain so it's probably publicly visible) can create new votes.

These are the default settings:

![image](https://user-images.githubusercontent.com/249703/48359742-8c8a5300-e6d8-11e8-94ad-302c60694890.png)

I suggest only an account who owns a token in the organisation can create votes.

----

How did I discovered this issue?

I was testing the app and wanted to onboard some friends. Gave them instructions:
> Visit: https://rinkeby.aragon.org
> Open an existing organisation: foobar

I was planning to ask them for ETH address so that I could assign them tokens.

Realised that they can create an assignment themselves.

The process feels weird.

**Real life analogy:**
Onboarding at a company, it's the admin who creates mars@aragon.one

Or is it me filling the form to HR?

What if HR is publicly open and anyone can submit the form?

**Comment by bingen** [comment]
Fixed by #50
