### ISSUE TITLE
Fix test gas scripts

### ISSUE THREAD

**Issue by facuspagnuolo** [aragon/dao-kits#80]
Both multisig and democracy templates have a test gas script that are broken, they are importing a relative file `../index_local.js` that doesn't exist.

**Comment by sohkai** [comment]
I think that file gets created if the beta-kit is run... but I may be wrong cc @bingen

**Comment by bingen** [comment]
Yes but the problem is that it got renamed to `arapp_local` here: 72d7f1, but I forgot those 2 gas test scripts. Will fix it right away.
